version: "3.8"

services:
  app:
    build: .
    entrypoint: ["/bin/sh", "-c", "nginx -g 'daemon off;' & java -jar /var/app/target/p6-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./src/sqlite:/var/app/sqlite
    env_file:
      - .env
    ports:
      - "8080:80"
    extra_hosts:
      - "${P6_HOSTNAME}:${P6_IP_ADDRESS}"