version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src/sqlite:/var/app/sqlite
    env_file:
      - .env
    ports:
      - "8080:8080"
    extra_hosts:
      - "${P6_HOSTNAME}:${P6_IP_ADDRESS}"
