version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./src/main/java/com/example/p6:/var/app/main/java/com/example/p6
      - ./src/sqlite:/var/app/sqlite
    env_file:
      - .env
    ports:
      - "${P6_ADAPTER_PORT}:8080"
    platform: "linux/amd64"
    extra_hosts:
      - "${P6_HOSTNAME}:${P6_IP_ADDRESS}"

volumes:
    filestore:
        driver: local
