version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src/main/java/com/example/p6:/var/app/main/java/com/example/p6
      - ./src/sqlite:/var/app/sqlite
    env_file:
      - .env
    ports:
      - "${P6_ADAPTER_PORT}:${P6_ADAPTER_PORT}"
    platform: "linux/amd64"
    extra_hosts:
      - "p6-prd-mw:10.53.20.38"
