version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src/main/java/com/example/p6:/var/app/main/java/com/example/p6
    env_file:
      - .env
    ports:
      - "${P6_ADAPTER_PORT}:${P6_ADAPTER_PORT}"
    platform: linux/amd64