version: "3.8"

services:
  app:
    build: .
    # volumes:
    #   - src:/usr/java/jetty/webapps
    env_file:
      - .env
    ports:
      - "${P6_ADAPTER_PORT}:${P6_ADAPTER_PORT}"
    platform: linux/amd64