# ConfigMap
apiVersion: v1
data:
  P6_ADAPTER_PORT: "8080"
  P6_HOSTNAME: p6-prd-mw
  P6_IP_ADDRESS: 10.53.20.38
  P6_EXECUTION_INTERVAL: "15000"
  P6_DB_LOC=jdbc:sqlite: /var/app/sqlite/p6.db
kind: ConfigMap
metadata:
  labels:
    app: app
  name: p6-adapter-cm

# Persistent Volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv
  namespace: p6-adapter-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

# Deployment
# The ConfigMap is a GitHub secret, and the SecretKey is on the cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: p6-adapter-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: p6-adapter-cm
          env:
            - name: P6_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: P6_ENCRYPTION_KEY
                  name: p6-encryption-key
          image: ${CI_REGISTRY}/${CI_REGISTRY_PATH}:${GITHUB_RUN_NUMBER}-dev
          imagePullPolicy: Always
          name: app
          args: 
            - /bin/sh
            - -c
            - nginx -g "daemon off;" & java -jar /var/app/target/p6-0.0.1-SNAPSHOT.jar
          ports:
            - containerPort: 80
          resources: 
            limits:
              cpu: 1
              memory: 1G
          volumeMounts:
            - mountPath: /var/app/sqlite
              name: app-pv
      restartPolicy: Always
      volumes:
        - name: app-pv
          persistentVolumeClaim:
            claimName: app-pv

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-ingress
  namespace: p6-adapter-dev
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
  selector:
    app: app

# Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: p6-adapter-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "strict-transport-security";
      more_clear_headers "x-content-type-options";
      more_clear_headers "x-frame-options";
      more_clear_headers "content-security-policy";
      proxy_set_header X-Forwarded-Proto https;
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  rules:
    - host: ${NETWORKING_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-ingress
                port:
                  number: 80