name: build-dev
on:
  push:
    branches: ["development"]
  workflow_dispatch:
jobs:
  development:
    runs-on: [self-hosted]
    environment: development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Digital-Engineering/p6_deeplynx_adapter
          ref: development

      - shell: bash
        name: Add Certificates
        env:
          CERT: ${{ secrets.CERT }}
        run: |
          cd $GITHUB_WORKSPACE/src/lib
          echo $CERT > dldev.cer

      - shell: bash
        name: ACR build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          cd $GITHUB_WORKSPACE
          az cloud set --name AzureUSGovernment
          az login --service-principal -u $ACR_SP_USER -p $ACR_SP_PASSWORD --tenant $ACR_SP_TENANT
          az account set --subscription $ACR_SUBSCRIPTION
          az acr build -r $ACR_REGISTRY -t $ACR_PATH:$GITHUB_RUN_NUMBER-dev .

      - shell: bash
        name: Kubernetes Manifest Environment
        env:
          KUBE_CONFIGMAP: ${{secrets.KUBE_CONFIGMAP}}
          CI_REGISTRY: ${{secrets.CI_REGISTRY}}
          CI_REGISTRY_PATH: ${{secrets.CI_REGISTRY_PATH}}
          NETWORKING_HOST: ${{secrets.NETWORKING_HOST}}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          cd $GITHUB_WORKSPACE
          envsubst < kubernetes/development.yaml > kubernetes/manifest.yaml

      - uses: azure/setup-kubectl@v3

      - uses: azure/k8s-set-context@v3
        name: Configure K8s
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: deploy-service-account

      - uses: Azure/k8s-deploy@v4
        name: Deploy K8s Workload
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          name: ${{ secrets.AKS_CLUSTER_NAME }}
          namespace: p6-adapter-dev
          action: deploy
          force: true
          strategy: basic
          manifests: |
            kubernetes/manifest.yaml
